export const SKILLS = [
  { name: "HTML5", level: 100, color: "#E85D25", logo: "HTML5" },
  { name: "CSS3", level: 100, color: "#249CDA", logo: "CSS3" },
  { name: "Sass", level: 80, color: "#C96195", logo: "Sass" },
  { name: "Bootstrap", level: 60, color: "#533B78", logo: "Bootstrap" },
  { name: "Javascript", level: 80, color: "#EFD81D", logo: "Javascript" },
  { name: "Vue.js", level: 70, color: "#3FB27F", logo: "Vuejs" },
  { name: "Vuex", level: 70, color: "#33475B", logo: "Vuex" },
  { name: "Angular", level: 100, color: "#BD002E", logo: "Angular" },
  { name: "Node.js", level: 30, color: "#539e43", logo: "nodejs" },
  { name: "JQuery", level: 30, color: "#0864A7", logo: "JQuery" },
  { name: "Postman", level: 70, color: "#ff6c37", logo: "Postman" },
  { name: "Ionic", level: 60, color: "#367CF7", logo: "Ionic" },
  { name: "React.js", level: 70, color: "#50BBD7", logo: "Reactjs" },
  { name: "Wordpress", level: 30, color: "#207196", logo: "Wordpress" },
  { name: "Git", level: 70, color: "#E84E31", logo: "Git" },
  { name: "Typescript", level: 60, color: "#2D79C7", logo: "Typescript" },
  { name: "Java", level: 30, color: "#E88A32", logo: "Java" },
  { name: "NoSQL", level: 60, color: "#F7C52B", logo: "NoSQL" },
  { name: "Photoshop", level: 50, color: "#001D34", logo: "Photoshop" },
  { name: "Jira", level: 70, color: "#1A80FF", logo: "Jira" },
  { name: "AWS", level: 30, color: "#FF8E04", logo: "AWS" },
  { name: "C#", level: 30, color: "#953DAC", logo: "CSharp" },
];

export const WORK_EXPERIENCE = [
  {
    company: "Deloitte Digital",
    role: "Consultant / Frontend Feveloper",
    dateStart: "Oct 2021",
    dateEnd: "present",
    location: "Bucharest",
    companyLogo: "deloitte-digital",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "Angular",
      "Sass",
      "TypeScript",
      "REST",
      "Jira",
      "Confluence",
      "React",
      "Thymeleaf",
      "Mambu",
      "moment.js",
      "AWS Services",
      "Java",
    ],
    projects: [
      {
        name: "Client 1 - Alpha Team",
        country: "United Kingdom",
        startDate: "Oct 2021",
        endDate: "Jan 2022",
        industry: ["Banking", "Insurance"],
        technologies: ["Angular 8+", "RxJs", "Jira", "moment.js"],
        contribution: [
          "Wrote a tutorial about how to write clean code when working on the frontend side for Alpha Team",
          "Feature that show to the user the active policies into a responsive and interactive design",
          "Upgraded from Angular 8 to Angular 13",
          "Added consistency to the CSS and HTML code maintaining a good collaboration with the designer",
          "Added possibility to use a vocabulary for an easier translation",
          "Improved the user authentication flow and added more layers of security for the confidential information",
          "Adding the possibility of a Mid Term Adjustment to a policy",
          "Mentoring frontend colleagues",
        ],
      },
      {
        name: "Client 2",
        country: "Germany",
        startDate: "Feb 2022",
        endDate: "present",
        industry: ["Banking"],
        technologies: [
          "React",
          "Thymeleaf",
          "Mambu",
          "moment.js",
          "TypeScript",
          "AWS Services",
          "Java",
        ],
        contribution: [
          "Create new React components and upload them into Mambu",
          "Modify Java functions accordingly to Thymeleaf templates to create custom PDF files",
        ],
      },
    ],
  },
  {
    company: "IBM iX",
    role: "Frontend Feveloper",
    dateStart: "Dec 2018",
    dateEnd: "Oct 2021",
    location: "Bucharest",
    companyLogo: "ibm",
    technologies: [
      "Angular",
      "SharePoint",
      "Vagrant",
      "Ionic",
      "Sass",
      "TypeScript",
      "JQuery",
      "REST",
      "Capacitor",
      "RxJs",
      "React.js",
      "Adobe Experience Manager",
      "Jira",
      "Vue.js",
      "Firebase",
      "Vuex",
      "Unit Testing",
    ],
    projects: [
      {
        name: "Internship",
        country: "Romania",
        startDate: "Dec 2018",
        endDate: "Feb 2019",
        industry: [],
        technologies: [
          "HTML",
          "CSS",
          "JavaScript",
          "Angular",
          "RxJs",
          "Vue.js",
          "Vuex",
          "Firebase",
          "Ionic",
        ],
        contribution: [
          "Designing mobile-based features using Ionic, working in an agile team.",
        ],
      },
      {
        name: "Client 1",
        country: "Germany",
        startDate: "Mar 2019",
        endDate: "Mar 2020",
        industry: ["Insurance"],
        technologies: [
          "Angular",
          "Ionic",
          "Sass",
          "TypeScript",
          "REST",
          "Capacitor",
          "RxJs",
        ],
        contribution: [
          "Delivered a good quality presentation website for our client in order to present our projects to their customers, in a small amount of time so the client was able to see the results and to use it",
          "Investigated and solved some vulnerabilities from the applications",
          "Contributed actively on a project from March and until the end of November, by helping other colleagues with code review and implementing reusable components. I also helped taking decisions in business rules and in development process",
          "Participated in every meeting and decision in a proactive way in order to deliver a quality and clean code which meets the client requirements",
        ],
      },
      {
        name: "Client 2",
        country: "United Kingdom",
        startDate: "Mar 2020",
        endDate: "Mar 2020",
        industry: ["Retail"],
        technologies: ["react.js"],
        contribution: [
          "Redesigning the on-boarding process for non plastic material and packaging suppliers onto the materials library and imagining the presentation and navigation of the library in parallel",
          "Participated in discussions with the design and front-end team in order to clarify and suggest edits so the user can have a better experience using the website",
          "Created reusable pages using React.js which corresponds to the design",
          "Created dynamic forms using Formik framework for the registration of new plastic free materials",
        ],
      },
      {
        name: "Client 3",
        country: "United States",
        startDate: "Apr 2020",
        endDate: "Oct 2021",
        industry: ["E-Commerce"],
        technologies: [
          "Angular",
          "Sass",
          "TypeScript",
          "REST",
          "RxJs",
          "Adobe Experience Manager",
          "VirtualBox",
          "JQuery",
          "Unit Testing",
        ],
        contribution: [
          "Created new components and features for the application in a way that we can reuse them when it is need",
          "Helped both design and development departments to take decisions in order to deliver the best features",
          "Learned better ways to solve the problems that appears during the development",
          "Delivered WYSIWYG (What You See Is What You Get), a feature that wants to improve the customer experience regarding the promotional codes.The first phase included changing the design of both coupons and product promotions, including more descriptive text and a user-friendly design, changes made throughout the application, on all banners. In the same phase was included the creation of the right drawer, which replaces the pop-up with the description of the promotion or the description page for it, being available by clicking on the link with the coupon / promotion details. If there are multiple promotions for a single product, they are displayed as a total, and will be described accordingly in the right drawer. The second phase includes the implementation of the new API response, which includes a new possibility to process the offers, displaying the requirement quantity, following that on the stores where the feature is activated, to display and if the offer has been completed and benefit from it. The new treatment system is visible both in the coupon design, in the mini-cart or in the top menu, in the right drawer and in the product page",
        ],
      },
    ],
  },
  {
    company: "Groupe Renault",
    role: "Database Administrator",
    dateStart: "Jun 2017",
    dateEnd: "Sep 2017",
    location: "Bucharest",
    companyLogo: "renault",
    technologies: ["Matlab", "SQL", "Excel", "PowerPoint"],
    projects: [
      {
        name: "Drive your future",
        country: "Worldwide",
        startDate: "Jun 2017",
        endDate: "Sep 2017",
        industry: ["Automotive"],
        technologies: ["Matlab", "SQL", "Excel", "PowerPoint"],
        contribution: [
          "Generating reports using large amounts of data from company clients around the globe",
          "Database maintenance using my own Matlab scripts",
        ],
      },
    ],
  },
];
